"""Initial sync

Revision ID: b3351151a5d8
Revises: 
Create Date: 2026-07-23 14:41:38.742378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3351151a5d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ndc_records', 'is_fnf_email_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('ndc_records', 'is_fnf_revision_email_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('idx_user_access_reset_token_search', 'ndc_user_access', ['reset_token'], unique=False)
    op.create_unique_constraint(None, 'ndc_user_access', ['reset_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ndc_user_access', type_='unique')
    op.drop_index('idx_user_access_reset_token_search', table_name='ndc_user_access')
    op.alter_column('ndc_records', 'is_fnf_revision_email_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('ndc_records', 'is_fnf_email_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
